
rsadsi OBJECT IDENTIFIER ::= { iso(1) member-body(2) us(840) 113549 }
pkcs OBJECT IDENTIFIER ::= { rsadsi 1 }
pkcs-1 OBJECT IDENTIFIER ::= { pkcs 1 }
rsaEncryption OBJECT IDENTIFIER ::= { pkcs-1 1 }    -- RSA (PKCS #1 v1.5) key transport algorithm
md2WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 2 }    -- MD2 with RSA Encryption Identifier for MD2 checks...
md4withRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 3 }    -- PKCS #1 md4withRSAEncryption
md5WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 4 }    -- RSA (PKCS #1 v1.5) with MD5 signature Identifier ...
sha1-with-rsa-signature OBJECT IDENTIFIER ::= { pkcs-1 5 } | sha1WithRSAEncryption(5) | sha-1WithRSAEncryption(5)    -- ...
rsaOAEPEncryptionSET OBJECT IDENTIFIER ::= { pkcs-1 6 } | ripemd160WithRSAEncryption(6)    -- RSA Optimal Asymmetri...
id-RSAES-OAEP OBJECT IDENTIFIER ::= { pkcs-1 7 }    -- id-RSAES-OAEP
id-mgf1 OBJECT IDENTIFIER ::= { pkcs-1 8 }    -- id-mgf1
id-pSpecified OBJECT IDENTIFIER ::= { pkcs-1 9 }    -- id-pSpecified
id-RSASSA-PSS OBJECT IDENTIFIER ::= { pkcs-1 10 }    -- id-RSASSA-PSS
sha256WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 11 }    -- SHA256 with RSA Encryption
sha384WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 12 }    -- SHA384 with RSA Encryption
sha512WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 13 }    -- SHA512 with RSA Encryption
sha224WithRSAEncryption OBJECT IDENTIFIER ::= { pkcs-1 14 }    -- sha224WithRSAEncryption

pkcs-3 OBJECT IDENTIFIER ::= { pkcs 3 }
dhKeyAgreement OBJECT IDENTIFIER ::= { pkcs-3 1 }

pkcs-5 OBJECT IDENTIFIER ::= { pkcs 5 }
pbeWithMD2AndDES-CBC OBJECT IDENTIFIER ::= { pkcs-5 1 }    -- Password Based Encryption Algorithm Uses Data Encr...
pbeWithMD5AndDES-CBC OBJECT IDENTIFIER ::= { pkcs-5 3 }    -- Password Based Encryption Algorithm Uses Data Encr...
pbeWithMD2AndRC2-CBC OBJECT IDENTIFIER ::= { pkcs-5 4 }    -- Password Based Encryption Algorithm Uses RC2 in Ci...
pbeWithMD5AndRC2-CBC OBJECT IDENTIFIER ::= { pkcs-5 6 }    -- Password Based Encryption Algorithm Uses RC2 in Ci...
pbeWithMD5AndXOR OBJECT IDENTIFIER ::= { pkcs-5 9 }    -- Password Based Encryption Algorithm Uses XOR Uses MD5 ...
pbeWithSHA1AndDES-CBC OBJECT IDENTIFIER ::= { pkcs-5 10 }    -- Password Based Encryption Algorithm Uses Data En...
pbeWithSHA1AndRC2-CBC OBJECT IDENTIFIER ::= { pkcs-5 11 }    -- Password Based Encryption Algorithm Uses RC2 in ...
pBKDF2 OBJECT IDENTIFIER ::= { pkcs-5 12 }    -- PBKDF2 key derivation algorithm Defined in PKCS-5 Ver 2.0 as a...
pkcs5PBES2 OBJECT IDENTIFIER ::= { pkcs-5 13 }    -- PBES2 encryption scheme
pkcs5PBMAC1 OBJECT IDENTIFIER ::= { pkcs-5 14 }    -- PKCS #5 v2.0 message authentication scheme



digestAlgorithm OBJECT IDENTIFIER ::= { rsadsi 2 }    -- Digest algorithms
md2 OBJECT IDENTIFIER ::= { digestAlgorithm 2 }    -- Message Digest #2
md4 OBJECT IDENTIFIER ::= { digestAlgorithm 4 }    -- RSADSI Message Digest #4
md5 OBJECT IDENTIFIER ::= { digestAlgorithm 5 }    -- Message Digest #5 algorithm. Commonly used with RSA Digital...
hmacWithSHA1 OBJECT IDENTIFIER ::= { digestAlgorithm 7 }    -- HMAC-SHA-1 pseudorandom function for key generation defined ...
hmacWithSHA224 OBJECT IDENTIFIER ::= { digestAlgorithm 8 }    -- HMAC-SHA-224 message authentication scheme
hmacWithSHA256 OBJECT IDENTIFIER ::= { digestAlgorithm 9 }    -- HMAC-SHA-256 message authentication scheme
hmacWithSHA384 OBJECT IDENTIFIER ::= { digestAlgorithm 10 }    -- HMAC-SHA-384 message authentication scheme
hmacWithSHA512 OBJECT IDENTIFIER ::= { digestAlgorithm 11 }    -- HMAC-SHA-512 message authentication scheme



encryptionAlgorithm OBJECT IDENTIFIER ::= { rsadsi 3 }    -- Encryption Algorithm
rc2CBC OBJECT IDENTIFIER ::= { encryptionAlgorithm 2 }    -- Voice encryption using RC2-compatible (56 bit)...
rc2ECB OBJECT IDENTIFIER ::= { encryptionAlgorithm 3 }    -- RSADSI encryptionAlgorithm
rc4 OBJECT IDENTIFIER ::= { encryptionAlgorithm 4 }    -- RSA RC4 private key encryption algorithm without MAC
rc4WithMAC OBJECT IDENTIFIER ::= { encryptionAlgorithm 5 }    -- RSADSI encryptionAlgorithm
desx-CBC OBJECT IDENTIFIER ::= { encryptionAlgorithm 6 }    -- RSADSI encryptionAlgorithm
des-EDE3-CBC OBJECT IDENTIFIER ::= { encryptionAlgorithm 7 }   -- ANSI X9.52: Triple DES modes o...
rc5-CBC OBJECT IDENTIFIER ::= { encryptionAlgorithm 8 }    -- RSADSI encryptionAlgorithm
rc5-CBC-PAD OBJECT IDENTIFIER ::= { encryptionAlgorithm 9 }    -- RC5 symmetric cipher used with Cipher Block Chai...
CDMFCBCPad OBJECT IDENTIFIER ::= { encryptionAlgorithm 10 }    -- RSADSI encryptionAlgorithm Formerly called CDMFCB...
